# Site settings
title: Digital Media and Society
tag_text: Digital Media and Society
description: Ressources for the Seminar / SciencesPO SGL 2016-2017
url: "https://plrolle.github.io/digitalmediasociety/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
